#!/bin/sh

JDTLS_REPOSITORY=$1
JDTLS_VERSION=$2
JDTLS_CONFIG=$3
JDTLS_WORKSPACE=$4

java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.level=ALL \
     -noverify \
     -Xmx1G \
     -jar $JDTLS_REPOSITORY/plugins/org.eclipse.equinox.launcher_$JDTLS_VERSION.jar \
     -configuration $JDTLS_REPOSITORY/$JDTLS_CONFIG \
     -data $JDTLS_WORKSPACE

