#!/bin/sh

JDTLS_REPOSITORY=$1
JDTLS_LAUNCHER=$(ls $JDTLS_REPOSITORY/plugins/org.eclipse.equinox.launcher_*.jar)
JDTLS_CONFIG=$2
JDTLS_WORKSPACE=$3

java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.level=ALL \
     -noverify \
     -jar $JDTLS_LAUNCHER \
     -configuration $JDTLS_REPOSITORY/$JDTLS_CONFIG \
     -data $JDTLS_WORKSPACE \
     # http://www.nicolasbize.com/blog/7-tips-to-speed-up-eclipse/
     # disable bytecode verification (risky)
     # -Xverify:none 
     # turn on performance compiler optimizations
     -XX:+AggressiveOpts \
     # increase permanent generation space (where new objects are allocated)
     -XX:PermSize=512m -XX:MaxPermSize=512m \
     # increase min and max heap sizes (which includes young and tenured generations)
     -Xms512m -Xmx2048m \
     # increase heap size for the young generation
     -Xmn512m \
     # set stack size for each thread
     -Xss2m \
     # tweak garbage collection
     -XX:+UseParallelOldGC

