#!/bin/sh

JDTLS_REPOSITORY=$1
JDTLS_VERSION=$2
JDTLS_CONFIG=$3
JDTLS_WORKSPACE=$4

java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.level=ALL \
     -noverify \
     -jar $JDTLS_REPOSITORY/plugins/org.eclipse.equinox.launcher_$JDTLS_VERSION.jar \
     -configuration $JDTLS_REPOSITORY/$JDTLS_CONFIG \
     -data $JDTLS_WORKSPACE \
     --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED \
     # http://www.nicolasbize.com/blog/7-tips-to-speed-up-eclipse/
     # disable bytecode verification (risky)
     # -Xverify:none 
     # turn on performance compiler optimizations
     -XX:+AggressiveOpts \
     # increase permanent generation space (where new objects are allocated)
     -XX:PermSize=512m -XX:MaxPermSize=512m \
     # increase min and max heap sizes (which includes young and tenured generations)
     -Xms512m -Xmx2048m \
     # increase heap size for the young generation
     -Xmn512m \
     # set stack size for each thread
     -Xss2m \
     # tweak garbage collection
     -XX:+UseParallelOldGC

