#!/bin/bash

JDTLS_REPOSITORY=/home/lgranie/opt/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository

java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.level=ALL \
     -noverify \
     -Xmx1G \
     -jar $JDTLS_REPOSITORY/plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar \
     -configuration $JDTLS_REPOSITORY/config_linux \
     -data /mnt/c/workspace-poc \
     --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED

