#!/bin/bash

JDTLS_REPOSITORY=$1
JDTLS_VERSION=$2
JDTLS_CONFIG=$3
JDTLS_WORKSPACE=$4

java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.level=ERROR \
     -noverify \
     -Xmx1G \
     -jar $JDTLS_REPOSITORY/plugins/org.eclipse.equinox.launcher_$2.jar \
     -configuration $JDTLS_REPOSITORY/$JDTLS_CONFIG \
     -data $JDTLS_WORKSPACE \
     --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED

